name: flutter_onboarding
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.4.1
  http: ^0.13.6
  json_annotation: ^4.8.1
  strict: ^1.4.0
  flutter: 
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  injectable: ^2.1.1
  dio: ^5.1.2
  logger: ^1.3.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  lint: ^2.0.1
  pubspec_dependency_sorter: ^1.0.3
  injectable_generator: ^2.1.5
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter: 
  assets: 
    - assets/
  uses-material-design: true
